export const INIT_AUTH = 'INIT_AUTH';
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const START_FETCHING_CHALLENGES = 'START_FETCHING_CHALLENGES';
export const RECEIVED_CHALLENGES = 'RECEIVED_CHALLENGES';
export const NEW_USER_CREATED = 'NEW_USER_CREATED';
